const ShoppingConstants = {
  GET_PRODUCT_LIST: "GET_PRODUCT_LIST",
  SET_PRODUCT_LIST: "SET_PRODUCT_LIST",

  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  GET_PRODUCTIDS_FROM_CART: "GET_PRODUCTIDS_FROM_CART",

  INCREASE_PRODUCT_QUANTITY: "INCREASE_PRODUCT_QUANTITY",
  DECREASE_PRODUCT_QUANTITY: "DECREASE_PRODUCT_QUANTITY",

  SET_TOTAL_COST: "SET_TOTAL_COST",
  SET_TOTAL_ITEMS: "SET_TOTAL_ITEMS",
  GET_TOTAL_ITEMS: "GET_TOTAL_ITEMS",
};

export default ShoppingConstants;
